"""
Export layer — converts a parsed analysis result into Markdown or PDF.
"""

from __future__ import annotations
from datetime import datetime


# ── Markdown export ────────────────────────────────────────────────────────────

def to_markdown(result: dict, code_snippet: str = "") -> str:
    """Return a formatted Markdown report string."""
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    model = result.get("model_used", "—")
    lang = result.get("language", "Unknown")

    confidence_raw = result.get("confidence", None)
    confidence_line = (
        f"| Confidence | {float(confidence_raw):.0%} |\n"
        if confidence_raw is not None else ""
    )

    code_block = ""
    if code_snippet.strip():
        ext = lang.lower() if lang.lower() not in ("unknown", "auto detect") else ""
        code_block = f"\n## Code Analyzed\n\n```{ext}\n{code_snippet.strip()}\n```\n"

    return f"""# Big-O Complexity Analysis Report

> Generated by **Big-O Complexity Analyzer** · {ts}

## Summary

| Field | Value |
|---|---|
| Model | `{model}` |
| Language | {lang} |
| Time Complexity | `{result.get("time_complexity", "—")}` |
| Space Complexity | `{result.get("space_complexity", "—")}` |
| Best Case | `{result.get("best_case", "—")}` |
| Worst Case | `{result.get("worst_case", "—")}` |
{confidence_line}
## Reasoning

{result.get("reasoning", "—")}

## Optimization

| Field | Value |
|---|---|
| Better Possible? | {result.get("better_possible", "N/A")} |
| Suggested Algorithm | {result.get("suggested_algorithm", "N/A")} |
| Expected Complexity | `{result.get("expected_complexity", "N/A")}` |
| Reason | {result.get("optimization_reason", "N/A")} |
{code_block}
---
*Report generated by Big-O Complexity Analyzer*
"""


# ── PDF export ─────────────────────────────────────────────────────────────────

def to_pdf(result: dict, code_snippet: str = "") -> bytes:
    """Return PDF bytes for the analysis report."""
    from fpdf import FPDF

    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    model = result.get("model_used", "—")
    lang = result.get("language", "Unknown")
    time_cx = result.get("time_complexity", "—")
    space_cx = result.get("space_complexity", "—")
    best = result.get("best_case", "—")
    worst = result.get("worst_case", "—")
    reasoning = result.get("reasoning", "—")
    better = result.get("better_possible", "N/A")
    sug_algo = result.get("suggested_algorithm", "N/A")
    exp_cx = result.get("expected_complexity", "N/A")
    opt_reason = result.get("optimization_reason", "N/A")

    confidence_raw = result.get("confidence", None)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # ── Title ──
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(0, 173, 181)
    pdf.cell(0, 12, "Big-O Complexity Report", ln=True)

    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 140)
    pdf.cell(0, 6, f"Generated: {ts}   |   Model: {model}   |   Language: {lang}", ln=True)
    pdf.ln(4)

    # ── Divider ──
    pdf.set_draw_color(0, 173, 181)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)

    # ── Complexity summary table ──
    def _section(title: str):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 173, 181)
        pdf.cell(0, 8, title, ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 60)

    def _row(label: str, value: str):
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(80, 80, 100)
        pdf.cell(55, 7, label, border="B")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(20, 20, 40)
        pdf.cell(0, 7, value, border="B", ln=True)

    _section("Complexity Metrics")
    _row("Time Complexity", time_cx)
    _row("Space Complexity", space_cx)
    _row("Best Case", best)
    _row("Worst Case", worst)
    if confidence_raw is not None:
        _row("Confidence", f"{float(confidence_raw):.0%}")
    pdf.ln(5)

    # ── Reasoning ──
    _section("Reasoning")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(40, 40, 60)
    pdf.multi_cell(0, 5, reasoning)
    pdf.ln(4)

    # ── Optimization ──
    _section("Optimization Suggestion")
    _row("Better Possible?", better)
    _row("Suggested Algorithm", sug_algo)
    _row("Expected Complexity", exp_cx)
    _row("Reason", opt_reason)
    pdf.ln(5)

    # ── Code snippet (truncated) ──
    if code_snippet.strip():
        _section("Code Analyzed")
        pdf.set_font("Courier", "", 8)
        pdf.set_text_color(30, 30, 50)
        snippet = code_snippet.strip()[:1200]
        if len(code_snippet.strip()) > 1200:
            snippet += "\n... (truncated)"
        pdf.multi_cell(0, 4.5, snippet)

    return bytes(pdf.output())
